# Generated by Django 4.1.4 on 2023-07-19 15:05

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=event.models.Event.upload_event_image)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
