# Generated by Django 4.1.4 on 2023-07-01 04:01

import asvs_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NgoLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('logo', models.ImageField(upload_to=asvs_app.models.NgoLogo.get_upload_path)),
            ],
        ),
    ]
