# Generated by Django 4.1.4 on 2023-07-01 04:25

import asvs_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asvs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to=asvs_app.models.Carousel.get_upload_path)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
